services:
  - type: web
    name: bloom-scheduler
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: GOOGLE_CREDENTIALS_B64
        sync: false
      - key: OPENAI_API_KEY
        sync: false

jobs:
  - type: cron
    name: fetch-gpt-events
    env: python
    schedule: "0 6 * * *"  # Запуск каждый день в 08:00 (UTC+2 = Paris)
    buildCommand: pip install -r requirements.txt
    startCommand: python fetch_events_from_gpt.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false

